spring:
  config:
    import: classpath:/env.yml
  datasource:
    url: ${gaori.mysql.host}
    username: ${gaori.mysql.username}
    password: ${gaori.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
  redis:
    host: ${gaori.redis.host}
    port: ${gaori.redis.port}
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: ${gaori.mail.port}
    username: ${gaori.mail.username}
    password: ${gaori.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.type: trace

jwt:
  header: Authorization
  accessTime: 3600000
  refreshTime: 2592000000
  prefix: Bearer
  secretKey: ${gaori.jwt.secretKey}
server:
  port: 8080

firebase:
  api:
    url: ${gaori.firebase.api.url}