name: gaori CI/CD
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Docker Login
        if: contains(github.ref, 'master')
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        if: contains(github.ref, 'master')
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .

      - name: Docker Push
        if: contains(github.ref, 'master')
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: google auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCE_SA_KEY }}"

      - name: set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: use gcloud cli
        run: "gcloud info"

      - name: gcp deploy
        run: |-
          gcloud compute instances update-container "${{ secrets.GCE_INSTANCE }}" \
            --zone "${{ secrets.GCE_INSTANCE_ZONE }}" \
            --container-image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: gcp reset
        run: |-
          gcloud compute instances reset "${{ secrets.GCE_INSTANCE }}" \
            --zone "${{ secrets.GCE_INSTANCE_ZONE }}"