name: Gaori CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Make application.yml
        run: | 
          cd ./src/main/resources
          touch ./env.yml
          echo "${{ secrets.ENV_YML }}" > ./env.yml
        shell: bash
        
      - name: Make firebase_service_key.json
        run: |
          cd ./src/main/resources
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" > ./firebase/firebase_service_key.json
        shell: bash

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Docker Build
        if: contains(github.ref, 'master')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docker Deploy executing remote ssh commands using ssh_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: 05tngus95
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker rm - f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
            docker-compose up -d
            docker image prune -f
